---
- hosts: all

  - name: Install requirements
    pip:
      requirements: /var/www/Flaskex/requirements.txt
      executable: pip3

  - name: Start Flaskex
    shell: "nohup python3 /var/www/Flaskex/app.py & "
    